name: collabothon-demo

services:
  gateway:
    image: nginx:1.27.1-alpine
    ports:
    - "8080:80"
    environment:
      NGINX_PORT: 80
    volumes:
    - type: bind
      source: ./gateway.conf
      target: /etc/nginx/nginx.conf
      read_only: true
    networks:
    - backend-mesh
    depends_on:
    - collabothon-api
    # - classifier-api
    - frontend

  collabothon-api:
    environment:
      LOGGING__LOGLEVEL__DEFAULT: Trace
      STHFISHY__LOGSENSITIVE: 'false'
      STHFISHY__DATABASEFILE: /data/demo.db
      STHFISHY__CLASSIFIER: http://classifier-api:8000/
      ASPNETCORE_URLS: http://0.0.0.0:80/
    env_file: backend.env
    image: collabothon-api:latest
    build:
      context: ./backend/
      dockerfile: ./SomethingFishy.Collabothon2024.API/Dockerfile
    user: root
    volumes:
    - collabothon-api-data:/data
    networks:
    - backend-mesh
    # depends_on:
    # - classifier-api

  # classifier-api:
  #   image: collabothon-classifier-api:latest
  #   build:
  #     context: "."
  #     dockerfile: Dockerfile
  #   networks:
  #   - backend-mesh
  #   ports:
  #   - 8000:8000

  frontend:
    image: collabothon-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
    - backend-mesh
    depends_on:
    - collabothon-api
    # - classifier-api

volumes:
  collabothon-api-data:

networks:
  backend-mesh:
